name: ProShop v2 CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  audit-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Recuperation du code
        uses: actions/checkout@v4

      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 2. Installation des dependances (Root)
        run: npm install

      - name: Installation des dependances (Frontend)
        run: |
          cd frontend
          npm install

      - name: 3. Execution des Tests
        run: echo "===== Execution des tests automatiques ====="

      - name: 4. Build de l'image Docker Backend
        run: docker build -t proshop-backend:latest -f backend/Dockerfile .

      - name: Build de l'image Docker Frontend
        run: docker build -t proshop-frontend:latest frontend/

      - name: 5. Analyse de securite (DevSecOps)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'proshop-backend:latest'
          format: 'table'
          severity: 'HIGH,CRITICAL'

      - name: 6. Simulation du Deploiement
        run: |
          echo "===== Pipeline valide avec succes ! ====="
          echo "Pret pour le deploiement avec Docker Compose"

      - name: 7. Connexion a Docker Hub
        uses: docker/login-action@v3
        with:
          # On utilise des variables secrete GitHub Actions pour ne pas exposer tes identifiants
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 8. Taguer et Pousser l'image Backend (v1.0 et latest)
        run: |
          docker tag proshop-backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/proshop-backend:latest
          docker tag proshop-backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/proshop-backend:v1.0
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/proshop-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/proshop-backend:v1.0